// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface SoldeStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SoldeStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>float sum = 2;</code>
   * @return The sum.
   */
  float getSum();

  /**
   * <code>float average = 3;</code>
   * @return The average.
   */
  float getAverage();
}
